export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
}

export const SpinnerType = {
  SHOW_SPINNER: "SHOW_SPINNER",
  SHOW_PRODUCTS: "SHOW_PRODUCTS"
}
export const SidebarType = {
  SHOW_SIDEBAR: "SHOW_SIDEBAR",
  HIDE_SIDEBAR: "HIDE_SIDEBAR"
}